### ISSUE TITLE
Q: How to filter by collection attribute

### ISSUE THREAD

**Issue by marcelstoer** [yaml-path/YamlPath#171]
Given the following YAML, I'd like to get all versions of 'foo'.

```yaml
component:
  - name: foo
    releases:
      - version: 12.0.0
        redirectOnly: false
      - version: 12.1.0
        redirectOnly: true
      - version: 12.1.1
        redirectOnly: true
  - name: bar
    releases:
      - version: 0.6.0
platform:
  - name: baz
    releases:
      - version: HEAD
        redirectOnly: false
```

I fail to understand how to get all `version`s of the `component` named `foo`.

I tried this and variations thereof (in Kotlin): `YamlPath.from(yamlString).read<Any>("(component[].name == foo).releases.version")`. However, any index expression (`[]`) without a number fails with a `NumberFormatException` which tells me I'm on the wrong track.
