### ISSUE TITLE
Matching filter

### ISSUE THREAD

**Issue by stasdavydov** [yaml-path/YamlPath#233]
I have a couple of YAMLs with different strctures:

```yaml
keyA:
  model_name: abc
...
```
```yaml
keyB:
  model_name: abc
...
```
```yaml
keyC:
  model_name: abc
...
```
```yaml
keyD:
  cases:
    - - model_name1
      - something...
    - - model_name2
      - something...
```

How to write a filter to get `model_name`s field from (1), (2), (3) (4)?

**Comment by Sgitario** [comment]
The hard part is from (4) because it does not follow a filterable convention (or at least, it's not supported by YamlPath).

Though, trying with:

```yaml
keyA:
  model_name: from_keyA
keyB:
  model_name: from_keyB
keyC:
  model_name: from_keyC
keyD:
  cases:
    - model_name: from_keyD_1
    - model_name: from_keyD_2
``` 

And using the path: `*.model_name` worked.
