### ISSUE TITLE
Allow to get the n-position of a list

### ISSUE THREAD

**Issue by Sgitario** [yaml-path/YamlPath#43]
For example, having the following YAML resource:
```yaml
apiVersion: v1
kind: Resource
metadata:
  name: "a name"
spec:
  args:
  - 1
  - 2
  - 3
```

Using the expression "spec.args", it would return a list of 1, 2, 3.

But we can't get a concrete position of these values. 

Implementation ideas:

Support expressions index-based like "spec.args[1]" that we would return "2".
